import { CarbonCredit, Transaction } from '@/types'

export const carbonCredits: CarbonCredit[] = [
  {
    id: 'crd-001',
    projectName: 'Amazon Rainforest Conservation',
    projectType: 'Forestry & Conservation',
    location: { country: 'Brazil', countryCode: 'BR', region: 'Amazonas' },
    certification: 'Verra VCS',
    vintage: 2023,
    pricePerCredit: 28,
    availableCredits: 15000,
    totalCredits: 50000,
    description: 'This project protects over 200,000 hectares of primary rainforest in the Brazilian Amazon, preventing deforestation and preserving critical biodiversity habitat.',
    methodology: 'VM0015 - Avoided Unplanned Deforestation',
    verificationDate: '2023-11-15',
    featured: true,
    image: '/images/amazon.jpg',
  },
  {
    id: 'crd-002',
    projectName: 'Gujarat Wind Farm',
    projectType: 'Renewable Energy',
    location: { country: 'India', countryCode: 'IN', region: 'Gujarat' },
    certification: 'Gold Standard',
    vintage: 2024,
    pricePerCredit: 22,
    availableCredits: 25000,
    totalCredits: 100000,
    description: 'A 150MW wind farm generating clean electricity for the Gujarat grid, displacing fossil fuel-based power generation.',
    methodology: 'ACM0002 - Grid-connected electricity generation from renewable sources',
    verificationDate: '2024-01-10',
    featured: true,
    image: '/images/wind.jpg',
  },
  {
    id: 'crd-003',
    projectName: 'Kenya Cookstove Distribution',
    projectType: 'Cookstove Distribution',
    location: { country: 'Kenya', countryCode: 'KE', region: 'Nairobi' },
    certification: 'Gold Standard',
    vintage: 2023,
    pricePerCredit: 18,
    availableCredits: 8000,
    totalCredits: 20000,
    description: 'Distribution of efficient cookstoves to rural communities, reducing wood fuel consumption and indoor air pollution.',
    methodology: 'TPDDTEC - Technologies and Practices to Displace Decentralized Thermal Energy Consumption',
    verificationDate: '2023-09-20',
    image: '/images/cookstove.jpg',
  },
  {
    id: 'crd-004',
    projectName: 'Texas Direct Air Capture',
    projectType: 'Direct Air Capture',
    location: { country: 'United States', countryCode: 'US', region: 'Texas' },
    certification: 'Verra VCS',
    vintage: 2024,
    pricePerCredit: 75,
    availableCredits: 2000,
    totalCredits: 5000,
    description: 'State-of-the-art direct air capture facility removing CO₂ directly from the atmosphere and storing it underground.',
    methodology: 'VM0044 - Direct Air Capture',
    verificationDate: '2024-02-01',
    featured: true,
    image: '/images/dac.jpg',
  },
  {
    id: 'crd-005',
    projectName: 'Indonesian Mangrove Restoration',
    projectType: 'Blue Carbon',
    location: { country: 'Indonesia', countryCode: 'ID', region: 'Kalimantan' },
    certification: 'Verra VCS',
    vintage: 2023,
    pricePerCredit: 32,
    availableCredits: 12000,
    totalCredits: 30000,
    description: 'Restoring degraded mangrove ecosystems along the Indonesian coastline, providing carbon sequestration and coastal protection.',
    methodology: 'VM0033 - Tidal Wetland and Seagrass Restoration',
    verificationDate: '2023-12-05',
    image: '/images/mangrove.jpg',
  },
  {
    id: 'crd-006',
    projectName: 'Chile Solar Farm',
    projectType: 'Renewable Energy',
    location: { country: 'Chile', countryCode: 'CL', region: 'Atacama' },
    certification: 'CDM',
    vintage: 2024,
    pricePerCredit: 19,
    availableCredits: 30000,
    totalCredits: 80000,
    description: 'A 200MW solar photovoltaic plant in the Atacama Desert, one of the sunniest places on Earth.',
    methodology: 'ACM0002 - Grid-connected electricity generation from renewable sources',
    verificationDate: '2024-01-25',
    image: '/images/solar.jpg',
  },
  {
    id: 'crd-007',
    projectName: 'German Landfill Methane Capture',
    projectType: 'Methane Capture',
    location: { country: 'Germany', countryCode: 'DE', region: 'Bavaria' },
    certification: 'Gold Standard',
    vintage: 2023,
    pricePerCredit: 24,
    availableCredits: 5000,
    totalCredits: 15000,
    description: 'Capturing and destroying methane from closed landfill sites, preventing release of potent greenhouse gases.',
    methodology: 'AMS-III.G - Landfill methane recovery',
    verificationDate: '2023-10-30',
    image: '/images/methane.jpg',
  },
  {
    id: 'crd-008',
    projectName: 'Ethiopian Reforestation',
    projectType: 'Forestry & Conservation',
    location: { country: 'Ethiopia', countryCode: 'ET', region: 'Amhara' },
    certification: 'Verra VCS',
    vintage: 2023,
    pricePerCredit: 15,
    availableCredits: 20000,
    totalCredits: 45000,
    description: 'Community-led reforestation project planting native tree species on degraded agricultural land.',
    methodology: 'AR-AMS0007 - Afforestation and Reforestation',
    verificationDate: '2023-08-15',
    image: '/images/reforestation.jpg',
  },
  {
    id: 'crd-009',
    projectName: 'Vietnam Energy Efficiency',
    projectType: 'Energy Efficiency',
    location: { country: 'Vietnam', countryCode: 'VN', region: 'Ho Chi Minh' },
    certification: 'CDM',
    vintage: 2024,
    pricePerCredit: 16,
    availableCredits: 18000,
    totalCredits: 40000,
    description: 'Industrial energy efficiency improvements across multiple manufacturing facilities in Vietnam.',
    methodology: 'AMS-II.D - Energy efficiency and fuel switching measures for industrial facilities',
    verificationDate: '2024-01-15',
    image: '/images/efficiency.jpg',
  },
  {
    id: 'crd-010',
    projectName: 'Morocco Wind Power',
    projectType: 'Renewable Energy',
    location: { country: 'Morocco', countryCode: 'MA', region: 'Tarfaya' },
    certification: 'Gold Standard',
    vintage: 2023,
    pricePerCredit: 21,
    availableCredits: 22000,
    totalCredits: 60000,
    description: 'Large-scale wind farm project contributing to Morocco\'s renewable energy transition.',
    methodology: 'ACM0002 - Grid-connected electricity generation from renewable sources',
    verificationDate: '2023-11-28',
    image: '/images/morocco-wind.jpg',
  },
  {
    id: 'crd-011',
    projectName: 'Peru Forest Protection',
    projectType: 'Forestry & Conservation',
    location: { country: 'Peru', countryCode: 'PE', region: 'Madre de Dios' },
    certification: 'Verra VCS',
    vintage: 2023,
    pricePerCredit: 26,
    availableCredits: 10000,
    totalCredits: 35000,
    description: 'Protecting pristine Amazon rainforest from illegal logging and agricultural conversion.',
    methodology: 'VM0007 - REDD+ Methodology Framework',
    verificationDate: '2023-10-10',
    image: '/images/peru-forest.jpg',
  },
  {
    id: 'crd-012',
    projectName: 'Bangladesh Biogas',
    projectType: 'Methane Capture',
    location: { country: 'Bangladesh', countryCode: 'BD', region: 'Dhaka' },
    certification: 'Gold Standard',
    vintage: 2024,
    pricePerCredit: 14,
    availableCredits: 15000,
    totalCredits: 25000,
    description: 'Household biogas systems converting agricultural waste into clean cooking fuel.',
    methodology: 'AMS-I.E - Switch from non-renewable biomass for thermal applications by the user',
    verificationDate: '2024-02-10',
    image: '/images/biogas.jpg',
  },
  {
    id: 'crd-013',
    projectName: 'Australian Savanna Burning',
    projectType: 'Forestry & Conservation',
    location: { country: 'Australia', countryCode: 'AU', region: 'Northern Territory' },
    certification: 'Verra VCS',
    vintage: 2023,
    pricePerCredit: 35,
    availableCredits: 6000,
    totalCredits: 18000,
    description: 'Indigenous-led early dry season burning reducing emissions from wildfires.',
    methodology: 'VM0004 - Conservation Projects',
    verificationDate: '2023-09-05',
    image: '/images/savanna.jpg',
  },
  {
    id: 'crd-014',
    projectName: 'Philippines Geothermal',
    projectType: 'Renewable Energy',
    location: { country: 'Philippines', countryCode: 'PH', region: 'Leyte' },
    certification: 'CDM',
    vintage: 2024,
    pricePerCredit: 20,
    availableCredits: 28000,
    totalCredits: 70000,
    description: 'Expansion of geothermal power generation utilizing volcanic activity.',
    methodology: 'ACM0002 - Grid-connected electricity generation from renewable sources',
    verificationDate: '2024-01-20',
    image: '/images/geothermal.jpg',
  },
  {
    id: 'crd-015',
    projectName: 'Colombia Watershed Protection',
    projectType: 'Forestry & Conservation',
    location: { country: 'Colombia', countryCode: 'CO', region: 'Antioquia' },
    certification: 'Gold Standard',
    vintage: 2023,
    pricePerCredit: 23,
    availableCredits: 9000,
    totalCredits: 22000,
    description: 'Protecting critical watershed forests that supply water to major cities.',
    methodology: 'AR-AMS0007 - Afforestation and Reforestation',
    verificationDate: '2023-12-18',
    image: '/images/watershed.jpg',
  },
]

export const transactions: Transaction[] = [
  {
    id: 'txn-001',
    type: 'buy',
    projectName: 'Amazon Rainforest Conservation',
    projectId: 'crd-001',
    quantity: 500,
    pricePerCredit: 28,
    totalAmount: 14000,
    date: '2024-01-10',
    status: 'completed',
    blockchainHash: '0x8f3e7a2d1c9b4e6f5a3d2c1b0a9e8f7d6c5b4a3e',
  },
  {
    id: 'txn-002',
    type: 'buy',
    projectName: 'Gujarat Wind Farm',
    projectId: 'crd-002',
    quantity: 1000,
    pricePerCredit: 22,
    totalAmount: 22000,
    date: '2024-01-08',
    status: 'completed',
    blockchainHash: '0x7e2d1c9b4a6f5e3d2c1b0a9e8f7d6c5b4a3e2f1d',
  },
  {
    id: 'txn-003',
    type: 'retire',
    projectName: 'Kenya Cookstove Distribution',
    projectId: 'crd-003',
    quantity: 200,
    pricePerCredit: 18,
    totalAmount: 3600,
    date: '2024-01-05',
    status: 'completed',
    certificateUrl: '/certificates/retire-001.pdf',
    blockchainHash: '0x6d1c9b4a5e6f3d2c1b0a9e8f7d6c5b4a3e2f1d0c',
  },
  {
    id: 'txn-004',
    type: 'buy',
    projectName: 'Indonesian Mangrove Restoration',
    projectId: 'crd-005',
    quantity: 750,
    pricePerCredit: 32,
    totalAmount: 24000,
    date: '2023-12-28',
    status: 'completed',
    blockchainHash: '0x5c9b4a3e6f5d2c1b0a9e8f7d6c5b4a3e2f1d0c9b',
  },
  {
    id: 'txn-005',
    type: 'retire',
    projectName: 'Amazon Rainforest Conservation',
    projectId: 'crd-001',
    quantity: 300,
    pricePerCredit: 28,
    totalAmount: 8400,
    date: '2023-12-20',
    status: 'completed',
    certificateUrl: '/certificates/retire-002.pdf',
    blockchainHash: '0x4b4a3e5f6d2c1b0a9e8f7d6c5b4a3e2f1d0c9b8a',
  },
  {
    id: 'txn-006',
    type: 'buy',
    projectName: 'Chile Solar Farm',
    projectId: 'crd-006',
    quantity: 500,
    pricePerCredit: 19,
    totalAmount: 9500,
    date: '2023-12-15',
    status: 'completed',
    blockchainHash: '0x3a3e4f5d6c2b1a0e9f8d7c6b5a4e3f2d1c0b9a8e',
  },
  {
    id: 'txn-007',
    type: 'buy',
    projectName: 'Texas Direct Air Capture',
    projectId: 'crd-004',
    quantity: 100,
    pricePerCredit: 75,
    totalAmount: 7500,
    date: '2023-12-10',
    status: 'completed',
    blockchainHash: '0x2e3f4d5c6b1a0e9f8d7c6b5a4e3f2d1c0b9a8e7d',
  },
  {
    id: 'txn-008',
    type: 'buy',
    projectName: 'Morocco Wind Power',
    projectId: 'crd-010',
    quantity: 400,
    pricePerCredit: 21,
    totalAmount: 8400,
    date: '2024-01-12',
    status: 'pending',
  },
]

export const getPortfolioSummary = () => {
  const portfolio = transactions
    .filter(t => t.type === 'buy' && t.status === 'completed')
    .reduce((acc, t) => {
      acc.totalCredits += t.quantity
      acc.totalValue += t.totalAmount
      return acc
    }, { totalCredits: 0, totalValue: 0 })

  const retired = transactions
    .filter(t => t.type === 'retire' && t.status === 'completed')
    .reduce((acc, t) => {
      acc.totalCredits += t.quantity
      return acc
    }, { totalCredits: 0 })

  return {
    totalOwned: portfolio.totalCredits - retired.totalCredits,
    totalValue: portfolio.totalValue,
    totalRetired: retired.totalCredits,
  }
}

export const getProjectTypeBreakdown = () => {
  const breakdown: Record<string, number> = {}

  transactions
    .filter(t => t.type === 'buy' && t.status === 'completed')
    .forEach(t => {
      const credit = carbonCredits.find(c => c.id === t.projectId)
      if (credit) {
        breakdown[credit.projectType] = (breakdown[credit.projectType] || 0) + t.quantity
      }
    })

  return Object.entries(breakdown).map(([name, value]) => ({ name, value }))
}

export const getCreditPriceTrends = () => {
  const months = ['Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan']

  return months.map((month, i) => ({
    month,
    'Forestry': 24 + Math.random() * 8,
    'Renewable Energy': 18 + Math.random() * 6,
    'Direct Air Capture': 68 + Math.random() * 15,
    'Blue Carbon': 28 + Math.random() * 8,
  }))
}
